checks with regex

diff --git a/.github/workflows/ruby.yml b/.github/workflows/ruby.yml
--- a/.github/workflows/ruby.yml
+++ b/.github/workflows/ruby.yml
@@ -222,7 +222,7 @@ jobs:
     needs: dist-build
     runs-on: ubuntu-latest
 #    if: github.ref_type == 'tag' && github.ref_name =~ ^v[0-9]+\.[0-9]+\.[0-9]+(\.[0-9a-z]+)?$
-    if: github.ref_type == 'branch' && github.ref_name == 'eyes-universal-4.1.3-ghactions'
+    if: github.ref_type == 'branch'
     env:
       TEST_REPORT_SANDBOX: False
 
@@ -230,22 +230,30 @@ jobs:
       - uses: actions/checkout@v3
       - name: ChangeLog check
         run: |
+          echo ${{ github.ref_name }}
+          if [[ (${{ github.ref_name }} =~ ^eyes-universal-4.1.3-ghactions$) ]]; then
+            echo 'pass'
+          fi
+          if [[ (${{ github.ref_name }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+(\.[0-9a-z]+)?$) ]]; then
+            echo 'fail'
+            exit 1
+          fi
           export TAG_VERSION='v4.1.2'
           export SDK_VERSION=$(echo $TAG_VERSION | sed 's/v[^.0-9a-z]*//g')
           echo $SDK_VERSION
 
           export TMP_CHANGELOG=$(bash ./extractChangeLog.sh "$SDK_VERSION" "CHANGELOG.md")
           export CHANGELOG=$([ -z "$TMP_CHANGELOG" ] && echo "There is no change log for version $SDK_VERSION"; echo "$TMP_CHANGELOG")
-        
+
+          echo $CHANGELOG
+          echo $TMP_CHANGELOG
+
           if [[ (-z "$TMP_CHANGELOG") ]]; then
             echo "THE CHANGELOG IS NOT CORRECT"
             exit 1
           fi
 
-          echo "v$SDK_VERSION $CHANGELOG"
-          echo $TMP_CHANGELOG
           COMMITTER_EMAIL="$(git log -1 ${{ github.ref_name }} --pretty="%cE")"
-          echo $COMMITTER_EMAIL
 
           if [[ ("$ALLOWED_RELEASE_COMMITERS" =~ .*"$COMMITTER_EMAIL".*) && $TMP_CHANGELOG ]]; then
             echo "DEPLOY";
